### ISSUE TITLE
Total Terminal ignores the theme

### ISSUE THREAD

**Issue by Nerian** [binaryage/totalterminal#1]
I am running Lion and Total Terminal 1.0

I have set a default profile named 'Nerian' which defines colours, background, etc. 

When I start Total Terminal it always uses the theme 'Visor', regardless of what the configured default theme is.

If I start a terminal – without Total Terminal – the theme in use is the right one.

http://dl.dropbox.com/u/834494/1.png
http://dl.dropbox.com/u/834494/2.png
http://dl.dropbox.com/u/834494/3.png

Any input?

PD: I am sorry for not using Get Satisfaction, but it seems that they have their login servers down right now :(

**Comment by Nerian** [comment]
I posted this in GetSatisfaction. I am closing the issue.

**Comment by darwin** [comment]
This is not a bug. This is by design. TotalTerminal uses Visor profile if available.
1. If you want to change theme, just change Visor theme (or rename Nerian to Visor).
2. Or alternatively when you delete Visor theme. TotalTerminal will use the default one.

**Comment by raulrene** [comment]
@darwin , where can I change/rename the Visor theme? I've just installed TotalTerminal 1.5.3 on OSX Yosemite and would like to use the Pro theme with it when pinned. In the terminal preferences no Visor theme appears. I've tried renaming the Pro one to Basic but nothing happens. Thanks in advance!

**Comment by darwin** [comment]
@raulrene In TotalTerminal preferences pane, you should have "Create Visor Profile" button. Use it, or alternatively you can rename any profile to "Visor" using Terminal's Profiles manager.

**Comment by cmfrtblynmb728** [comment]
@darwin thank you my friend
