### ISSUE TITLE
Use same shortcut for multiple users on one machine

### ISSUE THREAD

**Issue by freshy86** [binaryage/totalterminal#100]
Hi there,

I have the following problem with TotalTerminal: I have multiple users accounts on my Mac and I would like to use the same keyboard shortcut to bring TotalTerminal up on all my user accounts (I have to use one for work and a private one). But if I try to set the same shortcut for user account B that I have already configured on account A, I get an error that the keyboard shortcut is already a system wide shortcut (it's definitely not). If I change the shortcut for A, I can use it for B and vise versa, but it's never possible for A and B to have the same shortcut.

Is it possible to fix that? It's a bit annoying to change my workflow depending on which user account I'm using.

Thank you all for you great work here, TotalTerminal rocks!
Greetings from Germany

**Comment by darwin** [comment]
Workaround: just setup one user and then copy ~/Library/Preferences/com.apple.terminal.plist over to other accounts.

I will have to change shortcut recording component to be more flexible.

**Comment by darwin** [comment]
This should be fixed in 1.5.4
