### ISSUE TITLE
Single key shortcut for Total Terminal

### ISSUE THREAD

**Issue by gnsiva** [binaryage/totalterminal#101]
First off I'd like to thank you for creating this software I've been using it since it was Visor!

My problem is that I recently reformatted my MBA, and when I reinstalled total terminal it wouldn't allow me to make a single key shortcut. There's a key "§" on my MB which I don't even know what its supposed to be so I've had that as my terminal shortcut for ~4 years.

My muscle memory is not enjoying the change to two key shortcuts. Can you please make this allowed behaviour again, or let me know which was the last version that had it so I can go back?

Thanks

OS X Mavericks
Total Terminal 1.4.11

**Comment by darwin** [comment]
This is probably a limitation of my shortcut recording widget (UI component). You can tweak the plist directly if you know the keycode or have the old plist somewhere in a backup.

`~/Library/Preferences/com.apple.Terminal.plist` -> TotalTerminalShortcuts -> ToggleVisor ...

**Comment by gnsiva** [comment]
Thanks very happy to have my old shortcut back. Got it working though it was a bit of a faff.
So in case anyone wants to do this in the future:
- Close total terminal (I uninstalled as well)
- Restart the computer
- Open the file and edit after the <key>KeyCode</key> section
- <integer>10</integer>
- And after the <key>Modifiers</key> section
- <integer>8388608</integer>
- Reinstall/ start Total Terminal

_Closing_

**Comment by darwin** [comment]
:+1:

**Comment by arwidt** [comment]
This didnt work for me, the plist file gets overwrited after I did my changes.
Tell me if you fix it, I am able to set the § key as a shortcut in iTerm2, so it is possible.
Would love it if its possible for you to fix this.

**Comment by darwin** [comment]
Maybe you could use defaults command-line utility to manipulate plist files:
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/defaults.1.html
