### ISSUE TITLE
detect urls (underline?) & allow Command + click to open them

### ISSUE THREAD

**Issue by jonchui** [binaryage/totalterminal#103]
goobuntu already does this in terminal!

PS - TotalTerminal ROCKS!

**Comment by milgrim** [comment]
Terminal already does this. ctrl + click

**Comment by query** [comment]
You can also open them without using the context menu by holding down Cmd and double-clicking.

**Comment by darwin** [comment]
thanks for your comments, closing

**Comment by jonchui** [comment]
Awesome thanks!
