### ISSUE TITLE
Total terminal does not hide when switching away from it using Cmd+Tab 

### ISSUE THREAD

**Issue by peetonn** [binaryage/totalterminal#108]
Steps to reproduce:
1. Activate TotalTerminal (for instance, using shortcut ^')
**Result:** TotalTerminal slides from the top of the screen
2. Press Command+Tab and switch to another app 
**Result:** App is switched (it can be seen in the menu bar title), however TotalTerminal remains visible on top of it
**Expected result:** TotalTerminal will slide away after switching to another app

**Comment:** It used to work like that before update to version 1.4.10
OS X v10.9.4

**Comment by darwin** [comment]
Please check Main Menu Window -> Pin Visor (SHIFT+CMD+P)

Sometimes it gets enabled accidentally.

**Comment by peetonn** [comment]
Thanks, @darwin! That was the case.
