### ISSUE TITLE
Application doesn't work since OS X Yosemite Developer Preview 4

### ISSUE THREAD

**Issue by toydestroyer** [binaryage/totalterminal#109]
After update from OS X 10.10 DP 3 to 4 TotalTerminal doesn't work. Just launching Terminal.app.

**Comment by darwin** [comment]
http://discuss.binaryage.com/t/injection-fails-in-yosemite-dp4/2280

**Comment by huyphams** [comment]
follow above link or you can.
vim ~/.bash_profile
and add this script.
osascript -e "tell application \"Terminal\" to «event BATTinit»"
Thank you @darwin . I love Total Terminal so much.
Update: It's fixed. Thank you.
Checkout ver 1.5 http://totalterminal.binaryage.com/#changelog

**Comment by toydestroyer** [comment]
@darwin @huyphams thank you. But it is a dirty hack, right? Do you plan to fix this in the future?

**Comment by huyphams** [comment]
@toydestroyer  checkout version 1.5
http://totalterminal.binaryage.com/#changelog

**Comment by toydestroyer** [comment]
Thanks for the quick response!
