### ISSUE TITLE
terminals are forced to full screen size

### ISSUE THREAD

**Issue by omissis** [binaryage/totalterminal#110]
OSX Version: 10.9.3, 10.94
Total Terminal Version: 1.4.10, 1.4.11, 1.5

Since today all the tabs are resizing to the full size of the screen, no matter what. 

That happens when I start the app, when I open a new tab and when I show the terminals (for instance with double tab on a key).

Also resizing them manually using the inspector won't last: as soon as I do something TT will go back to full screen size.

I have no idea what could have caused this to happen, but maybe is due to some corrupted config file?

I attached a screenshot to get an idea of how it looks like.

![screen shot 2014-07-25 at 15 38 54 2](https://cloud.githubusercontent.com/assets/197604/3702604/1b11ca9a-1401-11e4-8151-f79f53c8631b.png)

Edit: I have also attached my config screen

![screen shot 2014-07-25 at 15 45 00](https://cloud.githubusercontent.com/assets/197604/3702685/fcb0d8a6-1401-11e4-9442-da62b73f5e32.png)

**Comment by darwin** [comment]
CMD+OPT+F (you have triggered it unintentionally, I guess) 

I'm sorry this is somewhat hidden feature, requested by someone. I should probably add an option for that or somehow visually indicate this special mode.

**Comment by omissis** [comment]
ah! that was it :)

thank you, I was going crazy :yum:

**Comment by darwin** [comment]
Sorry for that :-/
