### ISSUE TITLE
Turn the TotalTerminal as the active window.

### ISSUE THREAD

**Issue by nanernunes** [binaryage/totalterminal#114]
Dear, is there some way of when to call the TotalTerminal make it as the active Window on OSX?
I use a application that changes the keyboard layout based on the active window.

**Comment by darwin** [comment]
I think you can show Visor window via applescript. 

See "BATTvish" example here:
https://github.com/binaryage/totalterminal-osax

Similar thing you can achieve by invoking your Visor keyboard shortcut via applescript's System Events object.

Something like this:

```
tell application "System Events" 
    key code 123 using {control down, option down, command down}
end tell
```
