### ISSUE TITLE
system-wide hotkey issue

### ISSUE THREAD

**Issue by sjparker** [binaryage/totalterminal#115]
TotalTerminal issues a warning that the F7 key cannot be used as the hotkey because it is already being used as a system-wide hotkey. However, I've made sure that F7 is not bound system-wide AND I am able to bind it in TotalFinder's visor just fine (as a test). This is on Yosemite 10.10.

**Comment by darwin** [comment]
This should be resolved by v1.5.4. Please reopen if not.
