### ISSUE TITLE
dock over terminal

### ISSUE THREAD

**Issue by JulianWielga** [binaryage/totalterminal#16]
in lion dock is over terminal when bottom-positioned.

**Comment by darwin** [comment]
It was introduced in 1.1.1. I should probably add this as a preference.

http://getsatisfaction.com/binaryage/topics/force_total_terminal_to_always_display_on_top_of_the_dock

**Comment by A2K** [comment]
right, this should be a preference, I like how it works now because my dock has auto hide option on.

**Comment by glennfu** [comment]
I have my dock on the left and it doesn't hide itself and total terminal comes down from the top.  The dock covers important text all the time now, yuck!

**Comment by darwin** [comment]
You may switch it to the original behavior via
`defaults write com.apple.Terminal TotalTerminalVisorWindowOnHighLevel -bool YES`

as explained in under the link above

**Comment by darwin** [comment]
fixed in v1.1.2
