### ISSUE TITLE
Focus issue

### ISSUE THREAD

**Issue by blinkinglight** [binaryage/totalterminal#19]
scenario:
  press shorcut
  pin terminal
  select browser
  press shortcut 
     expected: hide totalterminal and keep browser on focus
     actual: shortcut set focus on total terminal and after second click - it hides

i think, that total teminal should hide, and keep focus on current window ( eg. browser )

**Comment by darwin** [comment]
This behavior is by design. Some people requested it and I think it makes sense to first return to pinned terminal and then close it with a second key press.
