### ISSUE TITLE
Terminal unexpectedly quits after shell exits

### ISSUE THREAD

**Issue by patricknixon** [binaryage/totalterminal#2]
After setting the "When the shell exits" option to "Close the window" or "Close if the shell exited cleanly", Terminal will crash if I _Ctrl-D_ to exit the running shell and only one tab is open.

I love visor, but I've always had an issue with the fact that I can't close the visor window.  I wish I could close it like any other window and expect that next time I _Ctrl-`_, a fresh terminal will open.

Thanks

**Comment by yanokwa** [comment]
i can post a number of crashlogs if they are needed...

**Comment by patricknixon** [comment]
this is fixed in 1.0.1
