### ISSUE TITLE
Can not use ctrl + ^ as shortcut

### ISSUE THREAD

**Issue by moschlar** [binaryage/totalterminal#20]
When I try to set ctrl + ^ as activation shortcut in Preferences, nothing happens. I just get the error sound and whatever was shortcut before is entered in the text field.

**Comment by waswrongassembled** [comment]
I've exactly the same issue!
(10.7; resetted all terminal settings and reinstalled TotalTerminal)

**Comment by waswrongassembled** [comment]
found a workaround:
- removed TT completely
- installed SIMBL with old VisorPlugin (http://visor.binaryage.com/#installation)
- changed HotKey
- installed TT  again (which removed visor ...)

--> works

**Comment by webflo** [comment]
Confirmed.

**Comment by darwin** [comment]
I was unable to reproduce it here on my machine so far (I have external keyboard).

I have updated shortcutrecorder codebase in 923280fa07375c602974c34cf98047f7a934daf5 there is a small chance that it fixed the issue

**Comment by elseym** [comment]
Same issue on Mountain Lion GM with TotalTerminal 1.3

Cannot record shortcuts ⌘+^ or ⌥+^ or ⌃+^.

**Comment by darwin** [comment]
Yes, I didn't spend more time on it. I'm sorry I'm not going to do it anytime soon.

**Comment by elseym** [comment]
Pity. Is there any way I can set the shortcut manually (plist, etc)?
Is there any particular reason it worked on 10.7 and stopped working on 10.8?

**Comment by moschlar** [comment]
I might add again, that I'm using 10.6, so the problem lies elsewhere
than the OS version.

Am 20.07.2012 20:29, schrieb elseym:

> Pity. Is there any way I can set the shortcut manually (plist, etc)?
> Is there any particular reason it worked on 10.7 and stopped working on 10.8?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/binaryage/totalterminal/issues/20#issuecomment-7137554

## 

Moritz Schlarb

**Comment by darwin** [comment]
~/Library/Preferences/com.apple.terminal.plist has the settings inside under TotalTerminalShortcuts key

but the modifiers and keycode you have to figure on your own, maybe @waswrongassembled can share?

@moschlar yes, it looks like it was caused by updating ShortcutRecorder code to some newer version. No related to OS version.

**Comment by elseym** [comment]
@darwin thanks a lot! works perfectly now.

Settings for ⌘+^ are:
  KeyCode: 10
  Modifiers: 1048576

**Comment by waswrongassembled** [comment]
Settings for ctrl + ^ (ML) are:
Keycode: 10
Modifiers: 262401

**Comment by jnettome** [comment]
Ctrl + ~:

Keycode: 50
Modifiers: 262144

**Comment by Bukashk0zzz** [comment]
Have similar problem with fn+§

Modifiers 8,388,608
KeyCode 10

Resolve problem by installing TotalTerminal 1.4.11 set shortcut fn+§ then update to 1.5.4

**Comment by darwin** [comment]
Is this still an issue in 1.5.4? I made the keyboard shortcut recorder less strict.

**Comment by Bukashk0zzz** [comment]
Yes. I tested today.

**Comment by egeerardyn** [comment]
I can also confirm this issue in 1.5.4: I tried setting Cmd+Ctrl+Space (even via the plist) and it just won't work. 
When loading the `plist` back, I can see the keys changing back to the old values in XCode.
In the settings the `Special Characters…` entry, however, is mapped to a different shortcut.
