### ISSUE TITLE
Since the latest update Cmd ~ doesn't seem to work for switching from visor to an undocked window

### ISSUE THREAD

**Issue by phill-tornroth** [binaryage/totalterminal#21]
Cmd ~ was working fine for switching between my 'visor' terminal window, and my normal ones, until the recent update this past week or so. Now switching to a visor window doesn't work at all. Switching from one seems to half-work... it will move focus to the normal terminal window, but won't bring that window to the forefront.. past other applications.

**Comment by steeve** [comment]
I have the same issue too

**Comment by padi** [comment]
I also have this issue, I love TotalTerminal/Visor when I was still using Snow Leopard. Don't know if it happens just in Lion. It just doesn't feel right having to press cmd + ~ twice to manually hide Visor away from the screen.
