### ISSUE TITLE
Can't change colors by clicking 'More...' button

### ISSUE THREAD

**Issue by jozan** [binaryage/totalterminal#22]
I've tried to reset settings by deleting **~/Library/Preferences/com.apple.Terminal.plist**, by creating a new theme and I've even re-installed TotalTerminal but nothing seems to solve this issue.

When clicking 'More...' Preference window goes inactive (light gray) and stops responding until I've opened and closed TotalTerminal window and activated Preference window by clicking it.

Previously I've been able to click 'More...' button and change colors easily without any problems.

I'm using 10.6.8 (Snow Leopard).

**Comment by pdokas** [comment]
I can reproduce those symptoms exactly and I'm also using 10.6.8. I'll try deleting my prefs now to see if that alleviates the issue.

**Comment by pdokas** [comment]
Deleting my prefs and relaunching had no effect. Nor did doing that and simultaneously reinstalling TotalTerminal.

**Comment by JDex** [comment]
I'm seeing the same as well.  I downloaded 1.1.3 to see if it was a problem there, and it is. 10.6.8 changed something.

**Comment by Danimal4326** [comment]
Same here..  1.1.4 on OSX 10.6.8.
Deleting prefs does not fix issue.
Uninstalling and re-installing doesn't help
