### ISSUE TITLE
Visor strings in Totalterminal

### ISSUE THREAD

**Issue by juanpabloaj** [binaryage/totalterminal#25]
In terminal preferences, in Total terminal tab. Exists this strings
-  tab name : Visor 
-  in settings : "visor settings"

**Comment by darwin** [comment]
That is right. Visor is just one feature of TotalTerminal. Others are Terminal Colours, CopyOnSelect, etc.

The reason why I have renamed Visor -> TotalTerminal was mainly confusion between TotalFinder's Visor and Visor for Terminal.
