### ISSUE TITLE
Hide dock icon

### ISSUE THREAD

**Issue by xster** [binaryage/totalterminal#3]
Hello, 

It'd be nice to have an option to hide the dock icon completely.

Xiao

**Comment by jedahan** [comment]
and the alt-tab icon too...

**Comment by darwin** [comment]
This is not possible AFAIK,

You may set LSUIElement of Terminal.app's Info.plist to 1. So you will hide your Terminal both from the Dock and cmd-tab list. TotalTerminal doesn't want to modifying Terminal.app's files, so you have to do it manually.

http://stackoverflow.com/questions/4154531/prevent-an-application-to-be-show-in-the-cmd-tab-application-cycle

**Comment by denkristoffer** [comment]
One possible solution would be to let the user decide which app TotalTerminal should inject into, perhaps as an advanced setting or something. Then it would be possible to make a copy of Terminal, set it to agent and inject into that one, while regular terminal still had its Dock icon. Best of both worlds although it means an extra copy of Terminal lying around.

**Comment by jedahan** [comment]
lesser known issue with this setup: it makes the preferences window very hard to interact with, as putting up the terminal will make the preferences window disappear

**Comment by darwin** [comment]
In 1.4.2 you can specify hidden tweak and TotalTerminal switches Terminal.app into UIElement mode during runtime.

`defaults write com.apple.Terminal TotalTerminalHideDockIcon -bool YES`

**Comment by aamaras** [comment]
Not working for me in OSX 10.9, TotalTerminal 1.4.2. 

Dock icon still visible, tried restarting the app, still there.

**Comment by darwin** [comment]
@popavo can you comment on this?

**Comment by popavo** [comment]
hmmm, with TotalTerminalHideDockIcon key set to true, it should just work. although sometimes setting defaults for an app that's currently running fails. 
@aamaras try running `do shell script "defaults write com.apple.Terminal TotalTerminalHideDockIcon -bool YES"` in AppleScript Editor. But make sure Terminal is not running

**Comment by aamaras** [comment]
Yep; ran it in AppleScript Editor and it works perfectly now. Thanks :smile:

**Comment by JoseAlban** [comment]
By the way, if people actually wants to CMD + Tab between totalterminal (v1.5.4) and other apps, you can still do `defaults write com.apple.Terminal TotalTerminalHideDockIcon -bool NO` and restart it.

**Comment by alwang27** [comment]
Fantastic! It really works.
