### ISSUE TITLE
Feature: Remove TotalTerminal from App Switcher

### ISSUE THREAD

**Issue by voidmain** [binaryage/totalterminal#30]
It would be nice to have an option to hide TotalTerminal from the App Switcher (cmd+tab). Since I only use it as a visor and never have stand-alone terminal windows open, it would be nice to hide it so that I don't end up selecting it by accident.

Another solution would be to open the visor if you switch to the application in the App Switcher and there are no windows open.

**Comment by chrischambers** [comment]
It would be good to have a convenient toggle for this, but the team mention why this isn't feasible and do provide a workaround, which I've adopted and works brilliantly:

> open /Applications/Utilities/Terminal.app/Contents/Info.plist and add LSUIElement entry and set it to true (in Property List > Editor is displays as "Application is agent (UIElement)").

If you're getting permission errors, the simplest possible workaround is to use 'Save as' to save the file to, say, the desktop, and then use `sudo mv ~/Desktop/Info.plist /Applications/Utilities/Terminal.app/Contents`

This has the effect of hiding TotalTerminal from the dock, and from cmd-tab switching.

**Comment by ghost** [comment]
I modified in the same way my Terminal.app. Would be nice if TotalTerminal had the option to do this modification even automatically, for example after a system update which restore Terminal to its  original behaviour.

**Comment by xeago** [comment]
```
Another solution would be to open the visor if you switch to the application in the App Switcher and there are no windows open.
```

This is currently implemented. This issue can be closed.

**Comment by darwin** [comment]
Since Mavericks you cannot touch Terminal.app's info.plist - it would break code signature.

Please follow #3 how to set LSUIElement flag dynamically with TotalTerminal 1.4.2+
