### ISSUE TITLE
Support iTerm2 instead of Terminal.app

### ISSUE THREAD

**Issue by dalgong** [binaryage/totalterminal#32]
Hi, 

I really like this but I really like [iTerm2](http://www.iterm2.com/#/section/home) instead of Terminal.app. It would be great to great to support iTerm2.

**Comment by reuben** [comment]
This makes me think the functionality is already available on iTerm2: http://www.iterm2.com/#/section/features/hotkey

**Comment by darwin** [comment]
iTerm2 has it's own Visor implementation. Also technically this is not easily possible to support both Terminal and iTerm2.
