### ISSUE TITLE
TotalTerminal.app won't load anymore

### ISSUE THREAD

**Issue by jcambien** [binaryage/totalterminal#33]
Hi, sorry in advance for bad english.

I was using TotalTerminal now for sereval days with no problems at all.
But today when i booted up my mac, he did not able to start for an unknown reason.
I tried to reinstall it multiple times, no luck.

There is the message i have when i run TotalTerminal.app through another terminal software (Coda) : 

2012-01-02 21:14:18.688 Terminal[1914:707] TotalTerminalInjector v1.1.4 received init event
2012-01-02 21:14:18.700 Terminal[1914:707] TotalTerminalInjector: Installing TotalTerminal ...
2012-01-02 21:14:18.702 Terminal[1914:707] Launching TotalTerminalCrashWatcher from '/Library/ScriptingAdditions/TotalTerminal.osax/Contents/Resources/TotalTerminal.bundle/Contents/Resources/TotalTerminalCrashWatcher.app'
2012-01-02 21:14:20.763 Terminal[1914:707] **\* Assertion failure in -[NSMenuItem setKeyEquivalent:], /SourceCache/AppKit/AppKit-1138.23/Menus.subproj/NSMenuItem.m:1019
2012-01-02 21:14:20.764 Terminal[1914:707] Invalid parameter not satisfying: aKeyEquivalent != nil
2012-01-02 21:14:20.765 Terminal[1914:707](0   CoreFoundation                      0x00007fff836a1286 __exceptionPreprocess + 198
        1   libobjc.A.dylib                     0x00007fff84f31d5e objc_exception_throw + 43
        2   CoreFoundation                      0x00007fff836a10ba +[NSException raise:format:arguments:] + 106
        3   Foundation                          0x00007fff8b4087d3 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 169
        4   AppKit                              0x00007fff864c930a -[NSMenuItem setKeyEquivalent:] + 138
        5   TotalTerminal                       0x000000010d42ead6 -[TotalTerminal%28Visor%29 updateHotKeyRegistration] + 501
        6   TotalTerminal                       0x000000010d418f0d -[TotalTerminal init] + 1522
        7   TotalTerminal                       0x000000010d4186bf +[TotalTerminal sharedInstance] + 52
        8   TotalTerminal                       0x000000010d4187db +[TotalTerminal delayedBoot] + 275
        9   Foundation                          0x00007fff8b34925a __NSFireDelayedPerform + 392
        10  CoreFoundation                      0x00007fff83655f84 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
        11  CoreFoundation                      0x00007fff83655ad6 __CFRunLoopDoTimer + 534
        12  CoreFoundation                      0x00007fff83636471 __CFRunLoopRun + 1617
        13  CoreFoundation                      0x00007fff83635ae6 CFRunLoopRunSpecific + 230
        14  HIToolbox                           0x00007fff87dc53d3 RunCurrentEventLoopInMode + 277
        15  HIToolbox                           0x00007fff87dcc63d ReceiveNextEventCommon + 355
        16  HIToolbox                           0x00007fff87dcc4ca BlockUntilNextEventMatchingListInMode + 62
        17  AppKit                              0x00007fff8649d3f1 _DPSNextEvent + 659
        18  AppKit                              0x00007fff8649ccf5 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 135
        19  AppKit                              0x00007fff8649962d -[NSApplication run] + 470
        20  AppKit                              0x00007fff8671880c NSApplicationMain + 867
        21  Terminal                            0x00000001097041a4 Terminal + 4516)

Any ideas ? 
Thanks for your help.

**Comment by darwin** [comment]
Julien, please delete your plist, it has probably stored some invalid
keyboard shortcut.

~/Library/Preferences/com.apple.Terminal.plist

(please backup that file prior deleting, maybe you'll want to transfer
some settings, or alternatively you may want to edit it in some plist
editor and remove all TotalTerminal-prefixed keys)
Antonin

On Mon, Jan 2, 2012 at 9:35 PM, Julien Cambien
reply@reply.github.com
wrote:

**Comment by jcambien** [comment]
It worked well, thank you! 
That was because i setted the F19 key as visor shortcut... 
Keep up the good work!

Julien

**Comment by jcambien** [comment]
Closing the issue... sorry, forgot it.
