### ISSUE TITLE
TotalTerminal working with iTerm2 (feature request)

### ISSUE THREAD

**Issue by mariozaizar** [binaryage/totalterminal#36]
Hello,

I really like TotalTerminal, I use it all day in my work and for my personal projects. It's really handy.
But, in fact I find more interesting iTerm 2 (http://iterm2.com/) than Terminal.app. I would love if TotalTerminal could use both.

**Comment by darwin** [comment]
This is not going to happen, see #32

**Comment by samyk** [comment]
I was using TotalTerminal until macOS Sierra as it now requires disabling SIP -- note that iTerm 2 has a similar feature: http://fokkezb.nl/2014/10/29/using-iterm2s-improved-visor/
