### ISSUE TITLE
Program launch confusion

### ISSUE THREAD

**Issue by apiarian** [binaryage/totalterminal#4]
The main website might do well with some sort of clarification of the installation/launch process. I came from the visor days when I just had to launch Terminal and the visor was started automatically. It took some figuring out (since I installed using the installer which hid this detail) that the proper way to launch Terminal with a visor is through TotalTerminal.app. Launching Terminal.app does not enable the visor feature automatically. It would have been nice to have this point expressly stated somewhere on the main installation page. (Incidentally, why does the program fail when I try to move it to the more logical /Applications/Utilities folder?)
Thanks for the great software!

**Comment by coneybeare** [comment]
Agreed.

**Comment by glennfu** [comment]
Even more awkward is that if you have TotalTerminal pinned in the dock, clicking it adds a 2nd icon to your dock as Terminal.  I would expect, like with every other OSX app, and with Visor before it, when you click the icon, that's the icon that the app uses.

**Comment by dmrschmidt** [comment]
1 up

**Comment by lucas-clemente** [comment]
+1

**Comment by darwin** [comment]
I agree with you guys. I was releasing it in a hurry to meet Lion release day.

Since v1.0.1 you can freely move TotalTerminal.app (but uninstaller still expects it in /Applications)

I've update the main website and consider this closed.
