### ISSUE TITLE
New "normal" window alongside TotalTerminal window

### ISSUE THREAD

**Issue by ghost** [binaryage/totalterminal#40]
With version 1.2.x upon the first invocation of TotalTerminal a new "normal" terminal window is opened too below the TotalTerminal one.
After closed doesn't appear anymore until Terminal is closed and TotalTerminal is relaunched.
This doesn't appen with 1.1.4.

I'm on Os X Lion fully updated and I set Terminal.app to not show up in the Dock (LSUIElement set to true)

**Comment by ygbr** [comment]
Bug present on Mountain Lion without LSUIElement hack too.

**Comment by darwin** [comment]
I don't force closing existing windows anymore: b4d2b4a9c650ac19295f3c506e7601d41f23ae13

Does this tweak help you?
`defaults write com.apple.Terminal TotalTerminalCloseWindowsOnStart -bool YES`

**Comment by ghost** [comment]
Yep that did it, thanks. There is a delay of few seconds though before I can actually invoke TotalTerminal.

**Comment by darwin** [comment]
2 seconds:
https://github.com/binaryage/totalterminal/blob/master/totalterminal-plugin/TotalTerminal.mm#L38-40

**Comment by ghost** [comment]
By restoration process (in the comment) you mean the feature introduced with Lion that saves the state of the app upon closing it (Resume)?
If yes, if I disable that feature for Terminal.app (defaults write com.apple.Terminal NSQuitAlwaysKeepsWindows -bool false) would be possible to eliminate that delay?

**Comment by darwin** [comment]
yes, some people put TotalTerminal.app into Startup Login Items and it
gets executed early and triggers Terminal.app launch

but this delay is mostly for safety, you don't want to launch
Terminal.app and start messing with its internals during its
initialization

we may make that delay tweakable via plist, feel free to fork

On Thu, Mar 1, 2012 at 3:39 PM, ranauei
reply@reply.github.com
wrote:

**Comment by ghost** [comment]
I use that exact configuration with Terminal.app icon hidden and such.
And I think that would be nice to have such feature built in. I mean to be able to set TotalTerminal to lauch automatically and at the same time to hide Terminal.app patching its Info.plist.
Also would be nice if the latter could be done automatically if TT detects that Terminal.app was restored in its original state, which happens at every system update.

**Comment by darwin** [comment]
I didn't want to modify any Terminal.app files, not only because there is risk of system updates, but also because people have various workflows and it may interfere with them.

I don't want to hang on support all day long. If you really want to do LSUIElement you should know what your are doing and what are the consequences.
