### ISSUE TITLE
TotalTerminal is crashing on OS X 10.8 DP1

### ISSUE THREAD

**Issue by zlowred** [binaryage/totalterminal#41]
Exception Name: NSInvalidArgumentException
Description: -[TTApplication newWindowControllerWithProfile:]: unrecognized selector sent to instance 0x7f89cbe0c3c0
User Info: (null)

0   CoreFoundation                      0x00007fff9174af06 **exceptionPreprocess + 198
1   libobjc.A.dylib                     0x00007fff973ef79a objc_exception_throw + 43
2   CoreFoundation                      0x00007fff917e42aa -[NSObject(NSObject) doesNotRecognizeSelector:] + 186
3   CoreFoundation                      0x00007fff9173956e ___forwarding_** + 414
4   CoreFoundation                      0x00007fff91739358 _CF_forwarding_prep_0 + 232
5   TotalTerminal                       0x000000010bcabec2 -[TotalTerminal(Visor) openVisor] + 105
6   TotalTerminal                       0x000000010bc937ed +[TotalTerminal delayedBoot] + 293
7   Foundation                          0x00007fff98cc0699 __NSFireDelayedPerform + 360
8   CoreFoundation                      0x00007fff91707e94 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
9   CoreFoundation                      0x00007fff917079ad __CFRunLoopDoTimer + 557
10  CoreFoundation                      0x00007fff916ed7e9 __CFRunLoopRun + 1497
11  CoreFoundation                      0x00007fff916eceb9 CFRunLoopRunSpecific + 233
12  HIToolbox                           0x00007fff970852d4 RunCurrentEventLoopInMode + 209
13  HIToolbox                           0x00007fff9708c4b2 ReceiveNextEventCommon + 356
14  HIToolbox                           0x00007fff9708c343 BlockUntilNextEventMatchingListInMode + 62
15  AppKit                              0x00007fff8ef4edab _DPSNextEvent + 685
16  AppKit                              0x00007fff8ef4e669 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 128
17  AppKit                              0x00007fff8ef4b2d3 -[NSApplication run] + 517
18  AppKit                              0x00007fff8f1bc78b NSApplicationMain + 869
19  libdyld.dylib                       0x00007fff962ba7e4 start + 0

**Comment by darwin** [comment]
This has been already fixed on pre-release channel. Download 1.2.2 or later:
http://totalterminal.binaryage.com/#changelog
