### ISSUE TITLE
Visor doesn't hide when focus shifts to another application

### ISSUE THREAD

**Issue by dbingham** [binaryage/totalterminal#42]
TotalTerminal 1.2.2:
Open visor, execute this command:
    $ open -a TextEdit

Notice that TextEdit opens and becomes the active application, but the Visor is still open.  To collapse it and get it out of the way, you have to hit the visor hotkey twice!  Once to refocus it, again to dismiss.

Note, this is NOT the same thing as TotalTerminalVisorForceHide.  Or at least, if it is, that tweak isn't working for this scenario.

**Comment by alexzielenski** [comment]
Turn off pinning...

**Comment by darwin** [comment]
yes, it must be pinned Visor - I was unable to reproduce it here with 1.2.2
