### ISSUE TITLE
Extra terminal window on startup with TotalTerminal 1.2.2

### ISSUE THREAD

**Issue by daniels220** [binaryage/totalterminal#44]
Just updated to 1.2.2 and now I get a new (non-Visor) terminal window when opening the terminal. This didn't happen in previous versions. I'm running OSX 10.6.8.

**Comment by darwin** [comment]
please follow #40

**Comment by daniels220** [comment]
Whoops, okay, fixed. IMO the old behavior should be the default, or something should be in the release notes—but regardless, closing issue as the plist change works for me.
