### ISSUE TITLE
A "stuck" window appears after closing main window

### ISSUE THREAD

**Issue by dangelov** [binaryage/totalterminal#45]
Steps to reproduce:

1) Close the last/only "visor" tab
2a) Press Cmd + N
2b) Activate another window and then click on the TotalTerminal dock icon

Edit: forgot to mention: Running TotalTerminal 1.2.2 on Mac OS X Lion 10.7.3

**Comment by darwin** [comment]
I was unable to reproduce it with TT1.3 under ML1.8.2. Please reopen if this is still an issue.
