### ISSUE TITLE
Make Cmd-1/2/3 switch between tabs not windows

### ISSUE THREAD

**Issue by MSch** [binaryage/totalterminal#46]
Pressing Command-1/2/3 switches between windows in Terminal.app, I would prefer if it switched between tabs in the current window, like it does in MacVim, Sublime Text, Chrome, ....

How much work do you think adding that feature would be?

**Comment by darwin** [comment]
it should be quite easy, but I don't have time for that :(

will definitely consider adding it next time I sit on hacking TotalTerminal

**Comment by sindresorhus** [comment]
:+1:

**Comment by jklmli** [comment]
:+1:

**Comment by MSch** [comment]
Any updates on this? Saw that you did some minor ML updates.

**Comment by macic** [comment]
Hey, any updates on this? :/

**Comment by darwin** [comment]
I have hard time to keep up with TotalFinder support and development. This is not high on my list. I'm sorry.

**Comment by rclarkburns** [comment]
Doesn't solve the problem but incase somebody stumbles across this looking for the keyboard shortcut to cycle through each open tab:

Next tab: Command + }
Previous tab: Command + {

**Comment by o2dazone** [comment]
While not a perfect solution, this can be done using SIMBL. http://superuser.com/questions/176177/unable-to-efficiently-switch-tabs-in-mac-terminal/176181#176181

It's not ideal, because it requires using SIMBL, and if you use TotalTerminal in LSUIElement mode (no dock icon), then you need to inject SIMBL into Terminal manually. https://code.google.com/p/simbl/issues/detail?id=9#c7

Good luck!

**Comment by darwin** [comment]
@o2dazone thanks for posting link to their code. This way it was much easier for me to implement. I didn't have to look for my solution and I just implemented it similar way what they have done.

This will be implemented in 1.4.6 which I will release later today on beta channel. Disabled by default. Enabled in preferences via "Tabs: Allow switching via CMD+<number>" checkbox

**Comment by MSch** [comment]
This has indeed been fixed by now and works on Yosemite. Thank you @darwin! The only problem I've got now is that I _only_ want tab switching with CMD+<number>, I don't want the Visor yet it can't be disabled :/

**Comment by darwin** [comment]
@MSch You could try to set hidden tweak via `defaults write com.apple.Terminal TotalTerminalDoNotOpenVisorDuringStartup -bool yes`

This should not create visor window unless you hit the keyboard shortcut (or menu item) for sliding it.
