### ISSUE TITLE
Feature Request: toggle background/foreground

### ISSUE THREAD

**Issue by machisuji** [binaryage/totalterminal#47]
Having a terminal available via global hotkey is mighty handy. What bothers me, though, is that it disappears entirely when using the hotkey again. I'm aware that this is part of the idea. However, I'd very much prefer if I could choose not to let the terminal disappear, but rather be put into the background. Toggling again should then bring it back forth.

Motivation: Every now and then I need to "manually" copy something from my terminal (Damn you Citrix!). For this it would be useful if the terminal didn't disappear but linger somewhere in the background instead, where I can still see it if my screen isn't too cluttered.

Dragging it out into a separate window is too bothersome.

This shouldn't be too difficult to implement it, or is it?
If no one is willing to do this then I'm gonna have to do it myself, though I'm not really familiar with Objective C and Mac development in general. :/

**Comment by joshbetz** [comment]
⌘⇧P pins the visor, if that's what you mean.

**Comment by darwin** [comment]
Yes, move the Citrix window somewhere where you can see it even with visor pulled down. Then pin the visor via ⌘⇧P, do the copy&pasting work. Don't forget to unpin visor when you are done.
