### ISSUE TITLE
Feature Request: New background color for new tabs

### ISSUE THREAD

**Issue by gposton** [binaryage/totalterminal#49]
I used to use Yaquake for Ubuntu, which had a feature I really liked.  It had an option to enable...

'When you open a new tab the background would be a different color.'  If I remember correctly, you could choose from a pastel color palette, greyscale palette, etc, but the colors aren't really the important part...

When working in multiple terminals all day, I'll occasionally type the a command in the wrong window.  We've all had that 'OH SH*T!!!' moment, but having the different background colors helps me quickly visually associate a tab with a server.

It would be great if the TotalTerminal remembered colors for particular servers (or if I could manually set them) and used the same color every time I log in to that server, but it would be valuable even if it didn't and just spun up a random new color for each new tab.

Thoughts?

**Comment by darwin** [comment]
If you want this functionality you can write some applescript which will open multiple tabs, set background colors and spawn some commands there.

I had such a script once and it worked pretty well. In Ruby:
https://github.com/darwin/drydrop/blob/master/rakefile#L192-221
