### ISSUE TITLE
Changing the font of the Visor display style kills TotalTerminal

### ISSUE THREAD

**Issue by ziegfried** [binaryage/totalterminal#6]
I've upgraded to TotalTerminal from Visor and now I'm unable to change the font settings for the Visor display style. When I change the font of Visor, the dropdown window does not work any more. Interestingly when killing Terminal.app and relaunching it, the Visor/TotalTerminal plugin seems to be gone. Only reinstalling helps.

**Comment by ziegfried** [comment]
Btw. this is on Snow Leopard

**Comment by tobsn** [comment]
i dont even know how to change anything... 

http://dl.dropbox.com/u/1656816/Screenshots/by16e-pmwjs1.png

does not look good. (default install)

**Comment by darwin** [comment]
can you please try again in 1.0.1?

I'm unable to reproduce it here.

btw. read homepage, there is a new explanation how you should be launching TotalTerminal via TotalTermina.app

**Comment by ziegfried** [comment]
Works like a charm in 1.0.1. Thx!
