### ISSUE TITLE
Update graphics to be retina-ready

### ISSUE THREAD

**Issue by darwin** [binaryage/totalterminal#65]
Forwarded conversation
## Subject: Total Terminal Retina

From: Rory Hardy gneatgeek@gmail.com
Date: Tue, Mar 26, 2013 at 7:36 PM
To: support@binaryage.com

Hello,

I was wondering if there was a way to get/make a retina version of the menu bar icon for Total Terminal?

Thanks

--Rory
All the best

---

---

---

From: BinaryAge Support support@binaryage.com
Date: Wed, Mar 27, 2013 at 1:17 PM
To: Rory Hardy gneatgeek@gmail.com

Ah, you are right. We need a new icon!

If you wanted to replace it yourself TotalTerminal's resources are here:
https://github.com/binaryage/totalterminal-i18n/tree/master/plugin

I will try to improve it with some new TotalTerminal release.
Antonin

**Comment by roryhardy** [comment]
I'll issue a pull request later once I make a new icon. Please assign me to this.
Thanks!

**Comment by sindresorhus** [comment]
@gneatgeek still interested? having a non-retina icon looks ugly in my otherwise pretty menubar.

**Comment by darwin** [comment]
@gneatgeek oh, I totally forgot. It would be cool. If you submit one I will include it in new release immediately.

**Comment by roryhardy** [comment]
Oh... I guess I issued the pull request to the wrong project?  https://github.com/binaryage/totalterminal-i18n/pull/5

Should i do I pull request here as well?

**Comment by darwin** [comment]
no, you did it right, I just forgot to include those files in the project

**Comment by roryhardy** [comment]
Ah ok.  So we're good then?  Should the issue be closed?

**Comment by darwin** [comment]
going to do it right now and see what happens :)

I will release an update in a few days, because I want to wait for feedback from users about new release and fix all issues at once.

**Comment by roryhardy** [comment]
Cool!  Excited to see it :)
