### ISSUE TITLE
External command to open new Tab in Visor window

### ISSUE THREAD

**Issue by notDavid** [binaryage/totalterminal#66]
Hi,
- I have a Visor window open with 2 tabs
- I hide the Visor window
- I open a Finder window
- I open [Alfred](http://www.alfredapp.com) and click "Open Terminal Here"
- I now get a **new Terminal window** instead of a _New Tab in the Current Visor Window_.

So, my question, is this possible by executing some Visor command to open a new tab in the already existing Visor window?

Thanks!
David.

**Comment by gharlan** [comment]
Open Alfred Preferences, Features, Terminal / Shell. 
Select Application "Custom" and paste this into the text box:

``` applescript
on alfred_script(q)
    tell application "Terminal"
        activate
        tell application "System Events" to tell process "Terminal.app" to keystroke "t" using command down
        do script q in front window
    end tell
end alfred_script
```

**Comment by notDavid** [comment]
Thank you!
