### ISSUE TITLE
Whenever I open total terminal it opens two windows, the original terminal and total terminal!

### ISSUE THREAD

**Issue by HughGrant** [binaryage/totalterminal#68]
and there is one more thing, my Visor theme is created by the button which I clicked in the total terminal preference and I set it as my default theme, but it seems it is not very colorful, actually it's all white except the font is bold. 

Can u help me out here?

**Comment by darwin** [comment]
=> https://github.com/binaryage/totalterminal/issues/43

**Comment by HughGrant** [comment]
thanks
