### ISSUE TITLE
Bring back "Stickyness"

### ISSUE THREAD

**Issue by RomainMuller** [binaryage/totalterminal#7]
Hi,

I was a great fan of having Visor being sticky (that is remain visible until I re-do the hotkey to hide it. I use it a great deal to monitor some background jobs in a fairly nonobstrusive way, or when I need to check on the output of some terminal command to do stuff in a GUI application. Can I get the "Sticky visor" back please?

Regards,
Romain.

**Comment by darwin** [comment]
This was fixed in v1.0.1. Look for Pin Visor under Window menu. You can change the keyboard shortcut in preferences.

**Comment by RomainMuller** [comment]
Oh, so it was only moved... Sorry I missed it...

**Comment by darwin** [comment]
No, it was really missing in 1.0 due to a bug.

**Comment by RomainMuller** [comment]
Oh okay. I got unsure because TotalTerminal did say it was up-to-date before I force re-downloaded it... I suppose 1.0.1 is too fresh ;)

**Comment by darwin** [comment]
1.0.1 is a pre-release. I didn't seed it to all "stable users".

still waiting for responses from beta testers

On Mon, Aug 1, 2011 at 4:51 PM, RomainMuller
reply@reply.github.com
wrote:

**Comment by RomainMuller** [comment]
Gotcha. Thanks anyway! This totally makes my day!
