### ISSUE TITLE
*Properly* hide TotalTerminal when it minimizes

### ISSUE THREAD

**Issue by marktheunissen** [binaryage/totalterminal#8]
It would be great if minimizing the terminal also hid it... i.e. the equivalent of hitting CMD + H on the application, so that it goes to the end of the application list in the ALT-TAB switcher.

This is because I often show the terminal, then close it using the hotkey, and then would like to alt-tab between two applications without alt-tabbing back to terminal, which won't open it anyway and is frustrating. 

So if it would auto-hide itself properly with OSX, then it would simulate the workflow whereby alt-tab switches between all apps except for terminal, and my hotkey is the launch command.

Thanks for the great app!

**Comment by darwin** [comment]
I see your point. The question is how this should behave when there are other classic Terminal windows. Or even with spaces. It is hard for me to imagine all implications of such a change.

**Comment by darwin** [comment]
ALT-TAB switcher behaves like you have described under Snow Leopard. I have just tested it under my Lion (10.7.2) and it does not work this way. After CMD+H application icon stays on the same spot in ALT-TAB switcher.

I don't know internal logic of different version of ALT-TAB switchers. TotatTerminal's Visor window simply hides from the screen ([window orderOut:nil]). This is the good behavior and I don't know how to improve it.
