### ISSUE TITLE
Hiding Terminal uses animation speed without animation

### ISSUE THREAD

**Issue by pstengel** [binaryage/totalterminal#80]
When using the activation hotkey to hide Terminal, the animation speed is always used even when no animation is selected. This means that the terminal will "stick" on screen until the animation timeout is reached.

You can "fix" this by manually typing `0` for the animation speed.

If no animation is selected, the animation speed should be ignored and the hiding of Terminal should be done immediately.

**Comment by pstengel** [comment]
An additional note: the manual fix is not perfect. There still seems to be a bit of stickiness, but it's not as bad as using the slider's minimum value of 0.1.

The best way to test this is to deselect all animations and decrease the animation speed to 1.0 second. Use the hotkey to show the terminal, then hit it again to hide it. It'll stay on screen for about a second before hiding.

**Comment by jamiew** [comment]
Can confirm the same. Seems to have started maybe around 1.4.3?

**Comment by jamiew** [comment]
Using "0" for animation speed and using an animation (e.g. fade) seems to correct this actually

**Comment by mukerjee** [comment]
Also can confirm. The "0" fix doesn't seem to help that much... When you first try it, it looks like it fixed it, but after a few tries the stickiness returns.
Hopefully this will get fixed soon.

**Comment by darwin** [comment]
Aren't you guys using quartz animations of background? There seems to be bug when you enable it (I don't use it personally).

I'm looking at the code and it should really do fast non-animated path when you set both fading and sliding off.

**Comment by pstengel** [comment]
I'm not animating the background. Settings are here:

https://www.dropbox.com/s/rtw58dxa6rr6416/Screenshot%202013-11-05%2008.47.09.png

Note that 1.4.5 is completely broken for me. There are artifacts when hiding the Terminal and I get delays no matter what I have set.

**Comment by darwin** [comment]
@pstengel btw. from the screenshot I see that you are using 1.4.4, but it should not make much difference to 1.4.5.

I'm considering removing new sliding code and going back to the original one in 1.3. We wanted to improve the code using NSAnimationContext's runAnimationGroup. But it was probably poor choice.

Wait for 1.4.6

**Comment by gmcmillan** [comment]
I'm having the same issue since I updated to 1.4 series. It is much quicker in 1.3 for me. It seems to have gotten worse in 1.4 for me, then really bad in 1.4.5 as @pstengel said. I am using 1.4.4 right now which is acceptable, but still feels slower than 1.3.

**Comment by mukerjee** [comment]
1.4.5 has no artifacts for me, but is really bad as @gmcmillan said.

**Comment by pstengel** [comment]
1.4.6 is working great. :smiley:

**Comment by mukerjee** [comment]
confirmed. 1.4.6 works great :)

**Comment by darwin** [comment]
Nice! Thanks for your cooperation.

**Comment by gmcmillan** [comment]
Just updated to 1.4.6 and it's great now. Thanks @darwin!
