### ISSUE TITLE
Visor doesn't resize after adjusting font size

### ISSUE THREAD

**Issue by jamiew** [binaryage/totalterminal#81]
Just upgraded to Mavericks and the latest TotalTerminal (1.4.3).

In previous versions, if I resized the font size of the visor (using cmd-+/-), closing the visor then re-opening would cause it to become full-width again.

Now I start with this:

![systemuiserver](https://f.cloud.github.com/assets/1903/1414165/99a9ac42-3e6e-11e3-92a6-0bc373611ef1.jpg)

Then after shrinking the font size – no matter how many times I close and re-open the visor:

![systemuiserver-1](https://f.cloud.github.com/assets/1903/1414169/b82af4e6-3e6e-11e3-8765-13893c33fa02.jpg)

Tweaking the Visor profile's default font size down and restarting gets it "back to normal", but I often resize the font on the fly.

**Comment by mukerjee** [comment]
This seems to be fixed in 1.4.5, at least for me.

**Comment by jamiew** [comment]
This is indeed fixed in 1.4.5. Thank you @binaryage!

**Comment by darwin** [comment]
ah, yes, I did some changes in this in 1.4.5
