### ISSUE TITLE
Visor won't exit full screen mode

### ISSUE THREAD

**Issue by spro** [binaryage/totalterminal#82]
I thought this problem was caused by Slate as my default full-screen toggle key is bound to Command-Option-F. However it seems that after disabling Slate I still cannot exit full screen mode after entering it, without manually changing the column amount in Terminal Preferences.

Occurs with 1.4.4, 1.4.3, 1.4.2 under OS X 10.8.5. Works fine with 1.3

**Comment by darwin** [comment]
Confirmed. Will look at it for 1.4.5 release.

**Comment by darwin** [comment]
Ah, I missed this issue with 1.4.5 and 1.4.6 release. Is it still the case with 1.4.6? (on beta channel right now).

**Comment by spro** [comment]
Just updated, looks good!
