### ISSUE TITLE
Switching to terminal opens total terminal

### ISSUE THREAD

**Issue by mglidden** [binaryage/totalterminal#83]
If I'm focused on a normal Terminal window, then switch to a different application and back, TotalTerminal re-opens over the normal window. This should only happen if TotalTerminal was previous selected or I hit the hotkey.

This bug is new to TotalTerminal 1.4.3.

**Comment by mglidden** [comment]
This only happens when using Command+Tab or the dock, and not when I click into terminal window itself.

**Comment by mfaerevaag** [comment]
Having the same issue on OS X 10.9 Mavericks.

**Comment by darwin** [comment]
v1.4.4 should fix that: http://totalterminal.binaryage.com/#changelog

**Comment by mfaerevaag** [comment]
Jepp, that fixed it for me!

A little note though, I was prompted with a password while updating? The dialogue said the update was protected by a password. I entered blank and that seemed to do it, but haven't seen this before. Bug?

**Comment by darwin** [comment]
This password thing has something to do with Sparkle updater I guess. I got reports from several people. I was not able to reproduce it on my machines so far...
