### ISSUE TITLE
Focus isn't restored after closing external commit editor

### ISSUE THREAD

**Issue by DrewAPicture** [binaryage/totalterminal#86]
OS X 10.8.5
TT v1.4.4

So, I use an external editor for vcs commit messages, and following the 1.4.3 update, the workflow changed when using TotalTerminal.

Pre-1.4.3, the workflow went something like this:
1. Initiate commit from TotalTerminal
2. External editor opens
3. Save and close commit message
4. Focus was automatically restored to TotalTerminal

Post-1.4.3 (now 1.4.4):
1. Initiate commit from Total Terminal
2. External editor opens
3. Save and close commit message
4. Have to manually switch back to TotalTerminal

It sounds like a little thing, but it adds just that little bit of extra time to my workflow that makes it irritating.

**Comment by star-szr** [comment]
Indeed! I noticed this right away.

**Comment by darwin** [comment]
This is important workflow for me as well. Just looking at it.

**Comment by darwin** [comment]
As I found out. This was introduced by dealing with #50. I did include this in 1.4+ releases and that is why we have this regression.

**Comment by darwin** [comment]
Unfortunately I had to add a new preferences option "Auto-slide when Terminal.app activates". I didn't find a way how to implement it without a new preference option to fit workflows of people in #50.

It will be available in 1.4.6. By default this is disabled.

**Comment by star-szr** [comment]
Thanks @darwin! I'm not sure I agree with the default being disabled, to me #50 sounds like the edge case here. Either way though I'm happy that I'll be able to continue using TotalTerminal the way I have been.

**Comment by darwin** [comment]
You are right. Let's make it enabled by default.

**Comment by DrewAPicture** [comment]
Works great, thanks for doing this :+1:

**Comment by star-szr** [comment]
Yes, thanks @darwin! This and #90 being fixed means TotalTerminal works like a dream for me again.
