### ISSUE TITLE
Visor window stretches entire screen on activation.

### ISSUE THREAD

**Issue by jgornick** [binaryage/totalterminal#87]
MacBook Pro Retina - OSX 10.8.5 - Dual-monitor setup - TotalTerminal 1.4.5

When I first open TotalTerminal, a normal terminal window appears then closes after a couple of seconds. Then, when I activate TotalTerminal to show the visor, the visor appears stretched to my entire screen. 

There is an option in the Window menu to "Return to Default Size" which seems to reset the visor dimensions to the columns and rows I have setup for my profile.

If I don't use the "Return to Default Size" option and `exit` in the visor window, it disappears. When I have TotalTerminal focused and open a new window via Command + N, then activate TotalTerminal, the window is now sized to the dimensions I've specified.

I should also mention that when I do get the window to display the dimensions I've specified, it's not respecting the Top-Center placement option I've selected.

**Comment by jgornick** [comment]
I should also point out that there is a difference between opening a new window via Command + N or clicking on the Terminal icon in the dock vs clicking the "Show Visor" option in the TotalTerminal menu extra icon menu. When using the new window option, it must create the window in the background, then in order for me to show the window, I need to activate TotalTerminal. If I use the "Show Visor" option, it opens the visor stretched to the dimensions of my screen.

**Comment by jgornick** [comment]
Thanks to @darwin I've been able to return my terminal to the proper size by CMD + OPTION + F (https://github.com/binaryage/totalterminal/issues/23#issuecomment-27900180)

**Comment by pudgereyem** [comment]
Thanks @jgornick, I had the same issue. Didn't think about CMD + Option + F.
