### ISSUE TITLE
Exiting Visor and clicking on the terminal application creates a smaller visor window

### ISSUE THREAD

**Issue by Deph0** [binaryage/totalterminal#88]
To reproduce, go into visor and type 'exit' (or cmd+w), and then reopen the visor by clicking on the terminal application and hotkey command to open the visor. 

if you have a stretch alternative, it will go into one position under it in the preference options, for example, if you use top-stretch, it will go top-left, and if you have right-stretch, it will be right-top if you close the visor with cmd+w (or similar)

E; using Macbook Air, OS 10.7.5, 2011 model, 13"

**Comment by darwin** [comment]
will be fixed in 1.4.6, thanks for reporting
