### ISSUE TITLE
delay when focusing away from total terminal

### ISSUE THREAD

**Issue by davidhq** [binaryage/totalterminal#90]
When I open TT and then close it either with Cmd+M or clicking on some other window, there is one second lag before the total terminal window disappears... I'm on Mountain Lion and use TT v1.4.5

**Comment by elliottkember** [comment]
+1 on this. Surprisingly annoying.

**Comment by darwin** [comment]
I did some significant changes in 1.4.6 (on beta channel right now). Please test it.

**Comment by davidhq** [comment]
much better! :)

**Comment by elliottkember** [comment]
:heart:
