### ISSUE TITLE
Terminal stays open on blur

### ISSUE THREAD

**Issue by zborboa-tesla** [binaryage/totalterminal#92]
Clicking off the terminal doesn't hide the terminal like it used to. Only when the Activation key is pressed twice, does the terminal hide. Even then "Terminal" is displayed in the top bar meaning it still has focus.

**Comment by pbihler** [comment]
Same for me. Despite it still says on the homepage:

> To hide Visor Window, you can either:
> (...)
> -    optionally, you can click off the TotalTerminal window

This is really a time thief...

**Comment by darwin** [comment]
Please check if you have not pinned visor accidentally: Main Menu -> Window -> Pin Visor

**Comment by zborboa-tesla** [comment]
@darwin - that was it. thanks!
