### ISSUE TITLE
Custom Icon With TotalTerminal

### ISSUE THREAD

**Issue by codeanpeace** [binaryage/totalterminal#99]
Custom Terminal icon gets replaced with default Terminal icon when TotalTerminal is launched. The selected preferences option "Keep the original Dock icon" somehow ignores the custom Terminal icon I substituted in for the default one.

**Comment by darwin** [comment]
Check in "Keep the original Dock icon" and restart both Terminal.app with TotalTerminal. There is no API to save original icon so I could swap it back.

**Comment by codeanpeace** [comment]
I understand that's what is supposed to happen, but for some odd reason it's not behaving as expected. When I launch TotalTerminal, the dock icon reverts back to the default icon regardless of whether I chose to "Keep the original Dock icon" or not - despite the fact that I have replaced the default icons for both Terminal and TotalTerminal with a custom one in the Content/Resources folder.

**Comment by darwin** [comment]
I have revisited the code and you are right. The default icon gets forced each time when TotalTerminal is launched.

**Comment by st40611** [comment]
Also having this problem. I am guessing/hoping this will be fixed in the next release?

**Comment by darwin** [comment]
Fixed in v1.5:
http://totalterminal.binaryage.com/#changelog
